M48
; DRILL file {KiCad (7.0.0)} date Wed Mar 22 16:00:19 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-22T16:00:19+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.0398Y-3.3195
X5.2673Y-3.3195
T2
X4.7677Y-3.1929
X4.7677Y-4.0315
X6.2953Y-3.1929
X6.2953Y-4.0315
T0
M30
